debug: false

logging:
  level:
    root: info

spring:
  application:
    name: ${artifactId}
  profiles:
    active: @mvn.profile.active@
  transaction:
    rollback-on-commit-failure: true
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    auto: true
    proxy-target-class: true
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8
    converters:
      preferred-json-mapper: jackson

mybatis:
  type-aliases-package: ${package}.model.domain;com.github.trang.typehandlers.alias
  type-handlers-package: com.github.trang.typehandlers.type
  mapper-locations: classpath:mappers/*.xml
  check-config-location: false
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#https://github.com/abel533/Mapper/tree/master/wiki/mapper3
mapper:
  mappers:
    - cn.org.easysite.spring.boot.tk.mybatis.core.mapper.CommonMapper
  not-empty: true
  identity: MYSQL

#https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
pagehelper:
  helper-dialect: mysql
  offset-as-page-num: true
  row-bounds-with-count: false
  page-size-zero: false
  reasonable: false
  support-methods-arguments: false
  auto-runtime-dialect: false
